// Copycats Sprüche (Sprechblase + Gebrabbel). mood: frech | wuetend | lachen | aufgeregt | fies
export const LINES = {
  round_start: { mood: 'frech', lines: [
    'Na, bereit für die nächste Runde?', 'Ich hab dich beobachtet. Die ganze Zeit!', 'Diesmal krieg ich dich, Clownsnase!',
    'Los geht\'s, Mango!', 'Mal sehen, was du heute falsch machst!', 'Tadaa! Da bin ich wieder!', 'Ich hab geübt. Vor dem Spiegel. Als du.',
  ] },
  hit_player: { mood: 'frech', lines: ['Treffer!', 'Erwischt!', 'Hab dich!', 'Das tat weh, oder?', 'Aua, sagst du jetzt.', 'Pling!'] },
  win: { mood: 'lachen', lines: [
    'Vorhersehbar!', 'Genau da hab ich dich erwartet!', 'Das war zu einfach!', 'Ich kenne dich besser als du dich selbst!',
    'Hahaha! Nochmal? Nochmal!', 'Applaus bitte! Für mich!',
  ] },
  lose: { mood: 'wuetend', lines: ['Glück gehabt!', 'Nächstes Mal kriege ich dich!', 'Ich lerne noch!', 'Das zählt nicht!', 'Na warte!', 'Ich hab mir alles gemerkt!'] },
  taunt: { mood: 'frech', lines: ['Schau mal, das bist du!', 'Na, gefällt dir mein Tanz?', 'Ich mach dich nach!', 'Lalala, du triffst mich nicht!', 'Guck mal, eine unsichtbare Wand!'] },
  hurt: { mood: 'wuetend', lines: ['Aua!', 'Hey! Das war Glück!', 'Ach komm schon!', 'Meine Mütze!', 'Unfair!'] },
  flag_warn: { mood: 'aufgeregt', lines: ['Gleich kommt die Flagge! Die gehört mir!', 'Flaggenzeit! Juhu!'] },
  flag_spawn: { mood: 'aufgeregt', lines: ['Die Flagge gehört mir!', 'Meins, meins, meins!'] },
  tutorial: { mood: 'frech', lines: ['Übe ruhig! Ich schaue zu!'] },
  learn_dodge_left: { mood: 'fies', lines: ['Du weichst immer nach links aus! Langweilig!'] },
  learn_dodge_right: { mood: 'fies', lines: ['Du weichst immer nach rechts aus! Wie süß!'] },
  learn_jump: { mood: 'fies', lines: ['Du springst ständig rum! Wie ein Flummi!'] },
  learn_adad: { mood: 'fies', lines: ['Links, rechts, links, rechts! Ich kenne deinen Rhythmus!'] },
  learn_heal_early: { mood: 'fies', lines: ['Du heilst dich viel zu früh! Angsthase!'] },
  learn_heal_late: { mood: 'fies', lines: ['Du heilst dich immer erst ganz am Ende!'] },
  learn_camper: { mood: 'fies', lines: ['Du versteckst dich gern! Ich finde dich trotzdem!'] },
  learn_rusher: { mood: 'fies', lines: ['Du stürmst immer blind nach vorne!'] },
  learn_close_weak: { mood: 'fies', lines: ['Aus der Nähe triffst du gar nichts!'] },
  learn_far_weak: { mood: 'fies', lines: ['Auf Distanz triffst du gar nichts!'] },
  learn_peek_left: { mood: 'fies', lines: ['Du kommst immer links aus der Deckung!'] },
  learn_peek_right: { mood: 'fies', lines: ['Du kommst immer rechts aus der Deckung!'] },
  learn_flag: { mood: 'fies', lines: ['Du rennst immer sofort zur Flagge!'] },
  learn_slide: { mood: 'fies', lines: ['Du rutschst so gerne! Ich jetzt auch!'] },
  learn_dash: { mood: 'fies', lines: ['Dash, Dash, Dash! Das kann ich auch!'] },
  learn_high: { mood: 'fies', lines: ['Du stehst so gerne oben! Ich weiß das!'] },
  learn_nothing: { mood: 'frech', lines: ['Noch weiß ich nicht viel über dich. Noch!'] },
};
