// Copycats Sprüche (Sprechblase + Gebrabbel). mood: frech | wuetend | lachen | aufgeregt | fies
export const LINES = {
  round_start: { mood: 'frech', lines: [
    'Na, bereit für die nächste Runde?', 'Ich hab dich beobachtet. Die ganze Zeit!', 'Diesmal krieg ich dich, Clownsnase!',
    'Los geht\'s, Mango!', 'Mal sehen, was du heute falsch machst!', 'Tadaa! Da bin ich wieder!', 'Ich hab geübt. Vor dem Spiegel. Als du.',
  ] },
  hit_player: { mood: 'frech', lines: ['Treffer!', 'Erwischt!', 'Hab dich!', 'Das tat weh, oder?', 'Aua, sagst du jetzt.', 'Pling!'] },
  win: { mood: 'lachen', lines: [
    'Vorhersehbar!', 'Genau da hab ich dich erwartet!', 'Das war zu einfach!', 'Ich kenne dich besser als du dich selbst!',
    'Hahaha! Nochmal? Nochmal!', 'Applaus bitte! Für mich!',
  ] },
  lose: { mood: 'wuetend', lines: ['Glück gehabt!', 'Nächstes Mal kriege ich dich!', 'Ich lerne noch!', 'Das zählt nicht!', 'Na warte!', 'Ich hab mir alles gemerkt!'] },
  taunt: { mood: 'frech', lines: ['Schau mal, das bist du!', 'Na, gefällt dir mein Tanz?', 'Ich mach dich nach!', 'Lalala, du triffst mich nicht!', 'Guck mal, eine unsichtbare Wand!'] },
  hurt: { mood: 'wuetend', lines: ['Aua!', 'Hey! Das war Glück!', 'Ach komm schon!', 'Meine Mütze!', 'Unfair!'] },
  flag_warn: { mood: 'aufgeregt', lines: ['Gleich kommt die Flagge! Die gehört mir!', 'Flaggenzeit! Juhu!'] },
  flag_spawn: { mood: 'aufgeregt', lines: ['Die Flagge gehört mir!', 'Meins, meins, meins!'] },
  tutorial: { mood: 'frech', lines: ['Übe ruhig! Ich schaue zu!'] },
  learn_dodge_left: { mood: 'fies', lines: ['Du weichst immer nach links aus! Langweilig!'] },
  learn_dodge_right: { mood: 'fies', lines: ['Du weichst immer nach rechts aus! Wie süß!'] },
  learn_jump: { mood: 'fies', lines: ['Du springst ständig rum! Wie ein Flummi!'] },
  learn_adad: { mood: 'fies', lines: ['Links, rechts, links, rechts! Ich kenne deinen Rhythmus!'] },
  learn_heal_early: { mood: 'fies', lines: ['Du heilst dich viel zu früh! Angsthase!'] },
  learn_heal_late: { mood: 'fies', lines: ['Du heilst dich immer erst ganz am Ende!'] },
  learn_camper: { mood: 'fies', lines: ['Du versteckst dich gern! Ich finde dich trotzdem!'] },
  learn_rusher: { mood: 'fies', lines: ['Du stürmst immer blind nach vorne!'] },
  learn_close_weak: { mood: 'fies', lines: ['Aus der Nähe triffst du gar nichts!'] },
  learn_far_weak: { mood: 'fies', lines: ['Auf Distanz triffst du gar nichts!'] },
  learn_peek_left: { mood: 'fies', lines: ['Du kommst immer links aus der Deckung!'] },
  learn_peek_right: { mood: 'fies', lines: ['Du kommst immer rechts aus der Deckung!'] },
  learn_flag: { mood: 'fies', lines: ['Du rennst immer sofort zur Flagge!'] },
  learn_slide: { mood: 'fies', lines: ['Du rutschst so gerne! Ich jetzt auch!'] },
  learn_dash: { mood: 'fies', lines: ['Dash, Dash, Dash! Das kann ich auch!'] },
  learn_high: { mood: 'fies', lines: ['Du stehst so gerne oben! Ich weiß das!'] },
  // Konter-Pläne (Copycat verrät, dass er dich durchschaut hat)
  counter_bait: { mood: 'fies', lines: ['Du stürmst immer rein? Dann warte ich hier auf dich!', 'Na komm, renn mir ruhig direkt vor die Nase!'] },
  counter_flank: { mood: 'fies', lines: ['Campen bringt dir nix. Ich komm von der Seite!', 'Versteck dich ruhig. Ich nehme einen anderen Weg!'] },
  counter_rushClose: { mood: 'frech', lines: ['Aus der Nähe triffst du nix. Also komm ich näher!', 'Nahkampf! Da bist du schlecht!'] },
  counter_keepFar: { mood: 'frech', lines: ['Auf Distanz bist du blind. Ich bleib schön weit weg!', 'Von weitem triffst du ja nix!'] },
  counter_high: { mood: 'frech', lines: ['Du willst wieder nach oben? Da bin ich schon!', 'Heute gehört der Ausblick mir!'] },
  // Schwächen ausnutzen
  push_heal: { mood: 'aufgeregt', lines: ['Am Heilen? Jetzt komm ich!', 'Spritze? Zu spät!'] },
  push_reload: { mood: 'aufgeregt', lines: ['Nachladen? Schlechte Idee!', 'Magazin leer? Perfekt!'] },
  push_low: { mood: 'fies', lines: ['Nur noch ein bisschen Leben, was? Gleich hab ich dich!', 'Du wackelst ja schon!'] },
  // Eigene Lage
  self_heal: { mood: 'wuetend', lines: ['Moment! Kurz verarzten!', 'Aua. Erst mal Pflaster drauf!'] },
  self_rush_low: { mood: 'wuetend', lines: ['Egal! Du bist genauso kaputt wie ich!', 'Alles oder nichts!'] },
  self_kite: { mood: 'frech', lines: ['Ich halt dich schön auf Abstand!'] },
  learn_nothing: { mood: 'frech', lines: ['Noch weiß ich nicht viel über dich. Noch!'] },
};
