// Automatisch erzeugt von tools/gen_voices.py – Spruch -> Audiodatei
export const VOICE = {
 "Na, bereit für die nächste Runde?": "audio/voice/round_start_0.mp3",
 "Ich hab dich beobachtet. Die ganze Zeit!": "audio/voice/round_start_1.mp3",
 "Diesmal krieg ich dich, Clownsnase!": "audio/voice/round_start_2.mp3",
 "Los geht's, Mango!": "audio/voice/round_start_3.mp3",
 "Mal sehen, was du heute falsch machst!": "audio/voice/round_start_4.mp3",
 "Tadaa! Da bin ich wieder!": "audio/voice/round_start_5.mp3",
 "Ich hab geübt. Vor dem Spiegel. Als du.": "audio/voice/round_start_6.mp3",
 "Neue Runde, neues Glück. Für mich!": "audio/voice/round_start_7.mp3",
 "Ich weiß schon, wo du gleich hinläufst.": "audio/voice/round_start_8.mp3",
 "Achtung, Vorhang auf!": "audio/voice/round_start_9.mp3",
 "Heute spiel ich dich besser als du!": "audio/voice/round_start_10.mp3",
 "Lauf ruhig. Ich find dich.": "audio/voice/round_start_11.mp3",
 "Treffer!": "audio/voice/hit_player_0.mp3",
 "Erwischt!": "audio/voice/hit_player_1.mp3",
 "Hab dich!": "audio/voice/hit_player_2.mp3",
 "Das tat weh, oder?": "audio/voice/hit_player_3.mp3",
 "Aua, sagst du jetzt.": "audio/voice/hit_player_4.mp3",
 "Pling!": "audio/voice/hit_player_5.mp3",
 "Genau da!": "audio/voice/hit_player_6.mp3",
 "Hab ich doch gewusst!": "audio/voice/hit_player_7.mp3",
 "Nicht ausgewichen?": "audio/voice/hit_player_8.mp3",
 "Kitzelt das?": "audio/voice/hit_player_9.mp3",
 "Bumm!": "audio/voice/hit_player_10.mp3",
 "Zack!": "audio/voice/hit_player_11.mp3",
 "Vorhersehbar!": "audio/voice/win_0.mp3",
 "Genau da hab ich dich erwartet!": "audio/voice/win_1.mp3",
 "Das war zu einfach!": "audio/voice/win_2.mp3",
 "Ich kenne dich besser als du dich selbst!": "audio/voice/win_3.mp3",
 "Hahaha! Nochmal? Nochmal!": "audio/voice/win_4.mp3",
 "Applaus bitte! Für mich!": "audio/voice/win_5.mp3",
 "Verbeugung! Danke, danke!": "audio/voice/win_6.mp3",
 "Du warst ein tolles Publikum!": "audio/voice/win_7.mp3",
 "Das hab ich mir von dir abgeschaut!": "audio/voice/win_8.mp3",
 "Und Vorhang!": "audio/voice/win_9.mp3",
 "Hihi. Zu langsam, Clownsnase!": "audio/voice/win_10.mp3",
 "War das schon alles?": "audio/voice/win_11.mp3",
 "Glück gehabt!": "audio/voice/lose_0.mp3",
 "Nächstes Mal kriege ich dich!": "audio/voice/lose_1.mp3",
 "Ich lerne noch!": "audio/voice/lose_2.mp3",
 "Das zählt nicht!": "audio/voice/lose_3.mp3",
 "Na warte!": "audio/voice/lose_4.mp3",
 "Ich hab mir alles gemerkt!": "audio/voice/lose_5.mp3",
 "Das war nur Aufwärmen!": "audio/voice/lose_6.mp3",
 "Revanche! Sofort!": "audio/voice/lose_7.mp3",
 "Grrr! Das merk ich mir!": "audio/voice/lose_8.mp3",
 "Pff. Anfängerglück.": "audio/voice/lose_9.mp3",
 "Moment, das war unfair!": "audio/voice/lose_10.mp3",
 "Ich komme wieder. Schlauer.": "audio/voice/lose_11.mp3",
 "Schau mal, das bist du!": "audio/voice/taunt_0.mp3",
 "Na, gefällt dir mein Tanz?": "audio/voice/taunt_1.mp3",
 "Ich mach dich nach!": "audio/voice/taunt_2.mp3",
 "Lalala, du triffst mich nicht!": "audio/voice/taunt_3.mp3",
 "Guck mal, eine unsichtbare Wand!": "audio/voice/taunt_4.mp3",
 "Hier drüben, Mango!": "audio/voice/taunt_5.mp3",
 "Juhu! Hallo!": "audio/voice/taunt_6.mp3",
 "Na? Kommst du?": "audio/voice/taunt_7.mp3",
 "Soll ich dir zeigen, wie das geht?": "audio/voice/taunt_8.mp3",
 "Einmal lächeln bitte!": "audio/voice/taunt_9.mp3",
 "Aua!": "audio/voice/hurt_0.mp3",
 "Hey! Das war Glück!": "audio/voice/hurt_1.mp3",
 "Ach komm schon!": "audio/voice/hurt_2.mp3",
 "Meine Mütze!": "audio/voice/hurt_3.mp3",
 "Unfair!": "audio/voice/hurt_4.mp3",
 "Autsch!": "audio/voice/hurt_5.mp3",
 "Nicht ins Gesicht!": "audio/voice/hurt_6.mp3",
 "Das gibt Rache!": "audio/voice/hurt_7.mp3",
 "Hey, das pikst!": "audio/voice/hurt_8.mp3",
 "Uff!": "audio/voice/hurt_9.mp3",
 "Gleich kommt die Flagge! Die gehört mir!": "audio/voice/flag_warn_0.mp3",
 "Flaggenzeit! Juhu!": "audio/voice/flag_warn_1.mp3",
 "Gleich wird's spannend!": "audio/voice/flag_warn_2.mp3",
 "Die Flagge kommt! Wer zuerst da ist!": "audio/voice/flag_warn_3.mp3",
 "Die Flagge gehört mir!": "audio/voice/flag_spawn_0.mp3",
 "Meins, meins, meins!": "audio/voice/flag_spawn_1.mp3",
 "Flagge! Ich renn schon!": "audio/voice/flag_spawn_2.mp3",
 "Wettrennen!": "audio/voice/flag_spawn_3.mp3",
 "Übe ruhig! Ich schaue zu!": "audio/voice/tutorial_0.mp3",
 "Du weichst immer nach links aus! Langweilig!": "audio/voice/learn_dodge_left_0.mp3",
 "Links, immer nach links. Ich weiß das jetzt!": "audio/voice/learn_dodge_left_1.mp3",
 "Schon wieder links? Ich ziel schon da hin!": "audio/voice/learn_dodge_left_2.mp3",
 "Du weichst immer nach rechts aus! Wie süß!": "audio/voice/learn_dodge_right_0.mp3",
 "Immer nach rechts. Ich hab's gesehen!": "audio/voice/learn_dodge_right_1.mp3",
 "Rechts ausweichen? Da wart ich schon!": "audio/voice/learn_dodge_right_2.mp3",
 "Du springst ständig rum! Wie ein Flummi!": "audio/voice/learn_jump_0.mp3",
 "Hopp, hopp, hopp! Ich weiß, wann du springst!": "audio/voice/learn_jump_1.mp3",
 "So viel Gehüpfe! Ich ziel einfach höher!": "audio/voice/learn_jump_2.mp3",
 "Links, rechts, links, rechts! Ich kenne deinen Rhythmus!": "audio/voice/learn_adad_0.mp3",
 "Hin und her, hin und her. Ich tanz einfach mit!": "audio/voice/learn_adad_1.mp3",
 "Dein Zickzack hab ich durchschaut!": "audio/voice/learn_adad_2.mp3",
 "Du heilst dich viel zu früh! Angsthase!": "audio/voice/learn_heal_early_0.mp3",
 "Schon wieder die Spritze? Du bist ja kaum verletzt!": "audio/voice/learn_heal_early_1.mp3",
 "Immer so früh heilen. Das merk ich mir!": "audio/voice/learn_heal_early_2.mp3",
 "Du heilst dich immer erst ganz am Ende!": "audio/voice/learn_heal_late_0.mp3",
 "Du wartest mit der Spritze bis zum letzten Moment!": "audio/voice/learn_heal_late_1.mp3",
 "Kurz vor knapp heilen? Dann bin ich da!": "audio/voice/learn_heal_late_2.mp3",
 "Du versteckst dich gern! Ich finde dich trotzdem!": "audio/voice/learn_camper_0.mp3",
 "Campen, campen, campen. Gähn!": "audio/voice/learn_camper_1.mp3",
 "Du bleibst gern stehen. Praktisch für mich!": "audio/voice/learn_camper_2.mp3",
 "Du stürmst immer blind nach vorne!": "audio/voice/learn_rusher_0.mp3",
 "Immer mit dem Kopf durch die Wand, was?": "audio/voice/learn_rusher_1.mp3",
 "Du rennst immer direkt auf mich zu. Danke!": "audio/voice/learn_rusher_2.mp3",
 "Aus der Nähe triffst du gar nichts!": "audio/voice/learn_close_weak_0.mp3",
 "Nah dran bist du ganz zittrig!": "audio/voice/learn_close_weak_1.mp3",
 "Je näher ich komme, desto schlechter zielst du!": "audio/voice/learn_close_weak_2.mp3",
 "Auf Distanz triffst du gar nichts!": "audio/voice/learn_far_weak_0.mp3",
 "Von weitem bist du blind wie ein Maulwurf!": "audio/voice/learn_far_weak_1.mp3",
 "Weit weg? Da triffst du ja nix!": "audio/voice/learn_far_weak_2.mp3",
 "Du kommst immer links aus der Deckung!": "audio/voice/learn_peek_left_0.mp3",
 "Links rausgucken. Jedes Mal!": "audio/voice/learn_peek_left_1.mp3",
 "Ich weiß, auf welcher Seite du rauskommst. Links!": "audio/voice/learn_peek_left_2.mp3",
 "Du kommst immer rechts aus der Deckung!": "audio/voice/learn_peek_right_0.mp3",
 "Rechts rausgucken. Jedes Mal!": "audio/voice/learn_peek_right_1.mp3",
 "Ich weiß, auf welcher Seite du rauskommst. Rechts!": "audio/voice/learn_peek_right_2.mp3",
 "Du rennst immer sofort zur Flagge!": "audio/voice/learn_flag_0.mp3",
 "Flagge da, Mango weg. Vorhersehbar!": "audio/voice/learn_flag_1.mp3",
 "Du kannst der Flagge einfach nicht widerstehen!": "audio/voice/learn_flag_2.mp3",
 "Du rutschst so gerne! Ich jetzt auch!": "audio/voice/learn_slide_0.mp3",
 "Rutschpartie? Kann ich auch!": "audio/voice/learn_slide_1.mp3",
 "So viel Gerutsche! Ich mach's dir nach!": "audio/voice/learn_slide_2.mp3",
 "Dash, Dash, Dash! Das kann ich auch!": "audio/voice/learn_dash_0.mp3",
 "Zisch! Dein Dash ist jetzt auch meiner!": "audio/voice/learn_dash_1.mp3",
 "Du ruckelst so schnell rum. Ich jetzt auch!": "audio/voice/learn_dash_2.mp3",
 "Du stehst so gerne oben! Ich weiß das!": "audio/voice/learn_high_0.mp3",
 "Immer rauf aufs Dach, was?": "audio/voice/learn_high_1.mp3",
 "Hoch oben bist du leicht zu finden!": "audio/voice/learn_high_2.mp3",
 "Noch weiß ich nicht viel über dich. Noch!": "audio/voice/learn_nothing_0.mp3",
 "Ich schau dir weiter zu!": "audio/voice/learn_nothing_1.mp3",
 "Hmm. Du bist schwer zu lesen. Noch!": "audio/voice/learn_nothing_2.mp3",
 "Ich schreib alles auf!": "audio/voice/inter_generic_0.mp3",
 "Mein Notizbuch wird immer dicker!": "audio/voice/inter_generic_1.mp3",
 "Nächste Runde bin ich schlauer!": "audio/voice/inter_generic_2.mp3",
 "Ich hab da so eine Idee...": "audio/voice/inter_generic_3.mp3",
 "Du wirst dich wundern!": "audio/voice/inter_generic_4.mp3",
 "Ich kenne jetzt deine Tricks!": "audio/voice/inter_generic_5.mp3",
 "Merk dir meine Worte!": "audio/voice/inter_generic_6.mp3",
 "Gleich geht's weiter. Freu dich!": "audio/voice/inter_generic_7.mp3",
 "Du stürmst immer rein? Dann warte ich hier auf dich!": "audio/voice/counter_bait_0.mp3",
 "Na komm, renn mir ruhig direkt vor die Nase!": "audio/voice/counter_bait_1.mp3",
 "Ich bleib hier sitzen. Du kommst ja eh.": "audio/voice/counter_bait_2.mp3",
 "Stürm ruhig los. Ich warte!": "audio/voice/counter_bait_3.mp3",
 "Campen bringt dir nix. Ich komm von der Seite!": "audio/voice/counter_flank_0.mp3",
 "Versteck dich ruhig. Ich nehme einen anderen Weg!": "audio/voice/counter_flank_1.mp3",
 "Schau lieber mal über die Schulter!": "audio/voice/counter_flank_2.mp3",
 "Ich schleich mich an!": "audio/voice/counter_flank_3.mp3",
 "Aus der Nähe triffst du nix. Also komm ich näher!": "audio/voice/counter_rushClose_0.mp3",
 "Nahkampf! Da bist du schlecht!": "audio/voice/counter_rushClose_1.mp3",
 "Ich komm ganz nah. Buh!": "audio/voice/counter_rushClose_2.mp3",
 "Kuscheln? Ich komm rüber!": "audio/voice/counter_rushClose_3.mp3",
 "Auf Distanz bist du blind. Ich bleib schön weit weg!": "audio/voice/counter_keepFar_0.mp3",
 "Von weitem triffst du ja nix!": "audio/voice/counter_keepFar_1.mp3",
 "Ich halt Abstand. Viel Glück!": "audio/voice/counter_keepFar_2.mp3",
 "Schön weit weg bleiben. Hihi.": "audio/voice/counter_keepFar_3.mp3",
 "Du willst wieder nach oben? Da bin ich schon!": "audio/voice/counter_high_0.mp3",
 "Heute gehört der Ausblick mir!": "audio/voice/counter_high_1.mp3",
 "Ich nehm heute den Logenplatz!": "audio/voice/counter_high_2.mp3",
 "Oben ist besetzt!": "audio/voice/counter_high_3.mp3",
 "Am Heilen? Jetzt komm ich!": "audio/voice/push_heal_0.mp3",
 "Spritze? Zu spät!": "audio/voice/push_heal_1.mp3",
 "Heilen? Nicht mit mir!": "audio/voice/push_heal_2.mp3",
 "Pflaster drauf? Ich komm trotzdem!": "audio/voice/push_heal_3.mp3",
 "Nachladen? Schlechte Idee!": "audio/voice/push_reload_0.mp3",
 "Magazin leer? Perfekt!": "audio/voice/push_reload_1.mp3",
 "Klick, klick? Jetzt ich!": "audio/voice/push_reload_2.mp3",
 "Leer geschossen? Hihi!": "audio/voice/push_reload_3.mp3",
 "Nur noch ein bisschen Leben, was? Gleich hab ich dich!": "audio/voice/push_low_0.mp3",
 "Du wackelst ja schon!": "audio/voice/push_low_1.mp3",
 "Gleich ist Schluss, Mango!": "audio/voice/push_low_2.mp3",
 "Noch ein Treffer!": "audio/voice/push_low_3.mp3",
 "Moment! Kurz verarzten!": "audio/voice/self_heal_0.mp3",
 "Aua. Erst mal Pflaster drauf!": "audio/voice/self_heal_1.mp3",
 "Auszeit! Kurz heilen!": "audio/voice/self_heal_2.mp3",
 "Nicht schießen, ich heil mich!": "audio/voice/self_heal_3.mp3",
 "Egal! Du bist genauso kaputt wie ich!": "audio/voice/self_rush_low_0.mp3",
 "Alles oder nichts!": "audio/voice/self_rush_low_1.mp3",
 "Jetzt oder nie!": "audio/voice/self_rush_low_2.mp3",
 "Wir sind beide fast hin. Los!": "audio/voice/self_rush_low_3.mp3",
 "Ich halt dich schön auf Abstand!": "audio/voice/self_kite_0.mp3",
 "Fang mich doch!": "audio/voice/self_kite_1.mp3",
 "Bleib mal schön da drüben!": "audio/voice/self_kite_2.mp3"
};
