// Automatisch erzeugt von tools/gen_voices.py – Spruch -> Audiodatei
export const VOICE = {
 "Na, bereit für die nächste Runde?": "audio/voice/round_start_0.mp3",
 "Ich hab dich beobachtet. Die ganze Zeit!": "audio/voice/round_start_1.mp3",
 "Diesmal krieg ich dich, Clownsnase!": "audio/voice/round_start_2.mp3",
 "Los geht's, Mango!": "audio/voice/round_start_3.mp3",
 "Mal sehen, was du heute falsch machst!": "audio/voice/round_start_4.mp3",
 "Tadaa! Da bin ich wieder!": "audio/voice/round_start_5.mp3",
 "Ich hab geübt. Vor dem Spiegel. Als du.": "audio/voice/round_start_6.mp3",
 "Treffer!": "audio/voice/hit_player_0.mp3",
 "Erwischt!": "audio/voice/hit_player_1.mp3",
 "Hab dich!": "audio/voice/hit_player_2.mp3",
 "Das tat weh, oder?": "audio/voice/hit_player_3.mp3",
 "Aua, sagst du jetzt.": "audio/voice/hit_player_4.mp3",
 "Pling!": "audio/voice/hit_player_5.mp3",
 "Vorhersehbar!": "audio/voice/win_0.mp3",
 "Genau da hab ich dich erwartet!": "audio/voice/win_1.mp3",
 "Das war zu einfach!": "audio/voice/win_2.mp3",
 "Ich kenne dich besser als du dich selbst!": "audio/voice/win_3.mp3",
 "Hahaha! Nochmal? Nochmal!": "audio/voice/win_4.mp3",
 "Applaus bitte! Für mich!": "audio/voice/win_5.mp3",
 "Glück gehabt!": "audio/voice/lose_0.mp3",
 "Nächstes Mal kriege ich dich!": "audio/voice/lose_1.mp3",
 "Ich lerne noch!": "audio/voice/lose_2.mp3",
 "Das zählt nicht!": "audio/voice/lose_3.mp3",
 "Na warte!": "audio/voice/lose_4.mp3",
 "Ich hab mir alles gemerkt!": "audio/voice/lose_5.mp3",
 "Schau mal, das bist du!": "audio/voice/taunt_0.mp3",
 "Na, gefällt dir mein Tanz?": "audio/voice/taunt_1.mp3",
 "Ich mach dich nach!": "audio/voice/taunt_2.mp3",
 "Lalala, du triffst mich nicht!": "audio/voice/taunt_3.mp3",
 "Guck mal, eine unsichtbare Wand!": "audio/voice/taunt_4.mp3",
 "Aua!": "audio/voice/hurt_0.mp3",
 "Hey! Das war Glück!": "audio/voice/hurt_1.mp3",
 "Ach komm schon!": "audio/voice/hurt_2.mp3",
 "Meine Mütze!": "audio/voice/hurt_3.mp3",
 "Unfair!": "audio/voice/hurt_4.mp3",
 "Gleich kommt die Flagge! Die gehört mir!": "audio/voice/flag_warn_0.mp3",
 "Flaggenzeit! Juhu!": "audio/voice/flag_warn_1.mp3",
 "Die Flagge gehört mir!": "audio/voice/flag_spawn_0.mp3",
 "Meins, meins, meins!": "audio/voice/flag_spawn_1.mp3",
 "Übe ruhig! Ich schaue zu!": "audio/voice/tutorial_0.mp3",
 "Du weichst immer nach links aus! Langweilig!": "audio/voice/learn_dodge_left_0.mp3",
 "Du weichst immer nach rechts aus! Wie süß!": "audio/voice/learn_dodge_right_0.mp3",
 "Du springst ständig rum! Wie ein Flummi!": "audio/voice/learn_jump_0.mp3",
 "Links, rechts, links, rechts! Ich kenne deinen Rhythmus!": "audio/voice/learn_adad_0.mp3",
 "Du heilst dich viel zu früh! Angsthase!": "audio/voice/learn_heal_early_0.mp3",
 "Du heilst dich immer erst ganz am Ende!": "audio/voice/learn_heal_late_0.mp3",
 "Du versteckst dich gern! Ich finde dich trotzdem!": "audio/voice/learn_camper_0.mp3",
 "Du stürmst immer blind nach vorne!": "audio/voice/learn_rusher_0.mp3",
 "Aus der Nähe triffst du gar nichts!": "audio/voice/learn_close_weak_0.mp3",
 "Auf Distanz triffst du gar nichts!": "audio/voice/learn_far_weak_0.mp3",
 "Du kommst immer links aus der Deckung!": "audio/voice/learn_peek_left_0.mp3",
 "Du kommst immer rechts aus der Deckung!": "audio/voice/learn_peek_right_0.mp3",
 "Du rennst immer sofort zur Flagge!": "audio/voice/learn_flag_0.mp3",
 "Du rutschst so gerne! Ich jetzt auch!": "audio/voice/learn_slide_0.mp3",
 "Dash, Dash, Dash! Das kann ich auch!": "audio/voice/learn_dash_0.mp3",
 "Du stehst so gerne oben! Ich weiß das!": "audio/voice/learn_high_0.mp3",
 "Du stürmst immer rein? Dann warte ich hier auf dich!": "audio/voice/counter_bait_0.mp3",
 "Na komm, renn mir ruhig direkt vor die Nase!": "audio/voice/counter_bait_1.mp3",
 "Campen bringt dir nix. Ich komm von der Seite!": "audio/voice/counter_flank_0.mp3",
 "Versteck dich ruhig. Ich nehme einen anderen Weg!": "audio/voice/counter_flank_1.mp3",
 "Aus der Nähe triffst du nix. Also komm ich näher!": "audio/voice/counter_rushClose_0.mp3",
 "Nahkampf! Da bist du schlecht!": "audio/voice/counter_rushClose_1.mp3",
 "Auf Distanz bist du blind. Ich bleib schön weit weg!": "audio/voice/counter_keepFar_0.mp3",
 "Von weitem triffst du ja nix!": "audio/voice/counter_keepFar_1.mp3",
 "Du willst wieder nach oben? Da bin ich schon!": "audio/voice/counter_high_0.mp3",
 "Heute gehört der Ausblick mir!": "audio/voice/counter_high_1.mp3",
 "Am Heilen? Jetzt komm ich!": "audio/voice/push_heal_0.mp3",
 "Spritze? Zu spät!": "audio/voice/push_heal_1.mp3",
 "Nachladen? Schlechte Idee!": "audio/voice/push_reload_0.mp3",
 "Magazin leer? Perfekt!": "audio/voice/push_reload_1.mp3",
 "Nur noch ein bisschen Leben, was? Gleich hab ich dich!": "audio/voice/push_low_0.mp3",
 "Du wackelst ja schon!": "audio/voice/push_low_1.mp3",
 "Moment! Kurz verarzten!": "audio/voice/self_heal_0.mp3",
 "Aua. Erst mal Pflaster drauf!": "audio/voice/self_heal_1.mp3",
 "Egal! Du bist genauso kaputt wie ich!": "audio/voice/self_rush_low_0.mp3",
 "Alles oder nichts!": "audio/voice/self_rush_low_1.mp3",
 "Ich halt dich schön auf Abstand!": "audio/voice/self_kite_0.mp3",
 "Noch weiß ich nicht viel über dich. Noch!": "audio/voice/learn_nothing_0.mp3"
};
